from enum import Enum


class Region(Enum):
    vinnytsia_region = "Vinnytsia Region"
    volyn_region = "Volyn Region"
    luhansk_region = "Luhansk Region"
    dnipropetrovsk_region = "Dnipropetrovsk Region"
    donetsk_region = "Donetsk Region"
    zhytomyr_region = "Zhytomyr Region"
    zakarpattia_region = "Zakarpattia Region"
    zaporizhzhia_region = "Zaporizhzhia Region"
    ivano_frankivsk_region = "Ivano-Frankivsk Region"
    kyiv_region = "Kyiv Region"
    kirovohrad_region = "Kirovohrad Region"
    lviv_region = "Lviv Region"
    mykolaiv_region = "Mykolaiv Region"
    odesa_region = "Odesa Region"
    poltava_region = "Poltava Region"
    rivne_region = "Rivne Region"
    sumy_region = "Sumy Region"
    ternopil_region = "Ternopil Region"
    kharkiv_region = "Kharkiv Region"
    kherson_region = "Kherson Region"
    khmelnytskyi_region = "Khmelnytskyi Region"
    cherkasy_region = "Cherkasy Region"
    chernihiv_region = "Chernihiv Region"
    chernivtsi_region = "Chernivtsi Region"
    autonomous_republic_of_crimea = "Autonomous Republic of Crimea"
    kyiv_city = "Kyiv City"
    sevastopol_city = "Sevastopol City"
