from enum import Enum


class Region(str, Enum):
    vinnytsia_region = "vinnytsia_region"
    volyn_region = "volyn_region"
    luhansk_region = "luhansk_region"
    dnipropetrovsk_region = "dnipropetrovsk_region"
    donetsk_region = "donetsk_region"
    zhytomyr_region = "zhytomyr_region"
    zakarpattia_region = "zakarpattia_region"
    zaporizhzhia_region = "zaporizhzhia_region"
    ivano_frankivsk_region = "ivano_frankivsk_region"
    kyiv_region = "kyiv_region"
    kirovohrad_region = "kirovohrad_region"
    lviv_region = "lviv_region"
    mykolaiv_region = "mykolaiv_region"
    odesa_region = "odesa_region"
    poltava_region = "poltava_region"
    rivne_region = "rivne_region"
    sumy_region = "sumy_region"
    ternopil_region = "ternopil_region"
    kharkiv_region = "kharkiv_region"
    kherson_region = "kherson_region"
    khmelnytskyi_region = "khmelnytskyi_region"
    cherkasy_region = "cherkasy_region"
    chernihiv_region = "chernihiv_region"
    chernivtsi_region = "chernivtsi_region"
    autonomous_republic_of_crimea = "autonomous_republic_of_crimea"
    kyiv_city = "kyiv_city"
    sevastopol_city = "sevastopol_city"
